### ISSUE TITLE
[Proposal] Remove Eclipse IDE project settings from git index

### ISSUE THREAD

**Issue by jensrudolf** [noseka1/linuxband#20]
Hi @noseka1,
currently, there are several Eclipse IDE related files checked into the git index:

- .settings
- .autotools
- .project
- .cproject
- .pydevproject

As the project can be build and installed completely by command line tooling (autotools), my proposal would be to remove these files from the index.
I know, there are different views whether to keep IDE project files within the index or not. However, as this is a relatively small project, I would guess it's very easy to set up whatever IDE or editor for development. I am using Visual Studio Code myself.
The reason I would propose to remove them, is keeping the project directory as clean and uncluttered as possible for every user/contributor and avoid unnecessary noise in the index in case e.g. there is a version change in one of the Eclipse plugins (they seem to be coded in the project files).
My recommendation would be to add these kind of files to your global user gitignore in $HOME/.gitignore or in the projects .git/info/exclude file as mentioned [here](https://dev.to/oleksiyrudenko/please-do-not-pollute-projects-gitignore-3h8e).

What do you think about it?

**Comment by noseka1** [comment]
Hi @jensrudolf,

Thanks for bringing this up. Was contemplating it for a while. I think that having a clean and uncluttered project as you mentioned is important. I am going to remove the Eclipse specific project files from git here shortly.

Also thanks for posting the link describing the global .gitignore configuration. That's exactly what I am going to do next.
