### ISSUE TITLE
Cannot lock down 82280346 byte memory area (Cannot allocate memory)

### ISSUE THREAD

**Issue by acorreya** [noseka1/linuxband#27]
Hi! i am trying play linuxband with the default setup/file/chords when opening. I launch linuxband from a terminal so that i can see what error comes and I get `Cannot lock down 82280346 byte memory area (Cannot allocate memory)` on the terminal. Linuxband window opens. Nothing shows on qjackctl/cadence so I push  [jack reconnect] and i get to see linuxband-player> as a midi out. I patch it to synth/through and then press [Play], which seems to be unresponsive and does not make anything happen. I press [Stop] and linuxband-player> disappears from qjackctl/cadence with below error:
`00:43:46 ERROR Failed to send data to midi player. Ensure the JACK server is running and hit the JACK reconnect button.` (repeated 4 times if that helps in debug).
Terminal spews: 
```
linuxband-player: src/main/c/midi.c:134: find_bar_end: Assertion 'end' failed.
00:43:46 ERROR __send_data Failed to send data to midi player. Ensure the JACK server is running and hit the JACK reconnect button.
00:43:46 ERROR __send_data...... 1 2 3 4 ....reconnect button.
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
```

I know it is some memory lock down error, but can you please help?

uname -a == `5.4.38-1-MANJARO #1 SMP PREEMPT Sat May 2 17:37:31 UTC 2020 x86_64 GNU/Linux`

**Comment by trebmuh** [comment]
[https://wiki.linuxaudio.org/wiki/system_configuration#limitsconfaudioconf]

**Comment by acorreya** [comment]
> [see here](https://wiki.linuxaudio.org/wiki/system_configuration#limitsconfaudioconf)

Thank you! i did this and it worked!
