### ISSUE TITLE
Crashes on run

### ISSUE THREAD

**Issue by slidesinger** [noseka1/linuxband#6]
Debian 7.0 with both ardour and musescore packages installed.  Installed the mma package from the developers website.  Tried compiling with both jack 1 and jack 2 following instructions on the Documentation page, not a python programmer, so I don't know how to fix this.  Here's what I have:

./configure
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for int8_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for working volatile... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working memcmp... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking return type of signal handlers... void
checking for working strtod... yes
checking for gettimeofday... yes
checking for memset... yes
checking for pow... no
checking for strdup... yes
checking for strerror... yes
checking for strtol... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GLIB... yes
checking for GTHREAD... yes
checking for JACK... yes
checking for SMF... yes
checking for JACK_MIDI_NEEDS_NFRAMES... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h

 make
cc -o target/linuxband-player  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include    -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -I.   -lglib-2.0   -pthread -lgthread-2.0 -lrt -lglib-2.0   -ljack -lpthread -lrt   -lsmf -lm -lglib-2.0   src/main/c/linuxband-player.c src/main/c/midi.c src/main/c/remote_control.c
sed \
          -e 's#[@]PACKAGE_NAME@#linuxband#g' \
          -e 's#[@]PACKAGE_VERSION@#12.02#g' \
          -e 's#[@]PACKAGE_BUGREPORT@#ales.nosek@gmail.com#g' \
          -e 's#[@]PACKAGE_URL@#http://linuxband.org#g' \
          -e 's#[@]PACKAGE_TITLE@#Linux Band#g' \
          -e 's#[@]PACKAGE_COPYRIGHT@#(c) 2012 Ales Nosek#g' \
          -e 's#[@]pkgdatadir@#/usr/local/share/linuxband#g' \
          -e 's#[@]pkglibdir@#/usr/local/lib/linuxband#g' \
          < "src/main/python/linuxband.py.in" > "target/linuxband"
sed \
          -e 's#[@]PACKAGE_VERSION@#12.02#g' \
          -e 's#[@]pkgdatadir@#/usr/local/share/linuxband#g' \
          < "src/main/config/linuxband.rc.in" > "target/linuxband.rc"

 make install
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -d /usr/local/lib/linuxband
/usr/bin/install -c -d /usr/local/share/linuxband
/usr/bin/install -c -t /usr/local/bin target/linuxband
/usr/bin/install -c -t /usr/local/lib/linuxband target/linuxband-player
/usr/bin/install -c -t /usr/local/share/linuxband target/linuxband.rc 
PY_SOURCE=$(cd src/main/python && find . -name '_.py'); \
        for F in ${PY_SOURCE}; do \
          /usr/bin/install -c -D src/main/python/$F /usr/local/share/linuxband/$F; done
/usr/bin/install -c -t /usr/local/share/linuxband src/main/config/default.mma
/usr/bin/install -c -t /usr/local/share/linuxband src/main/glade/gui.glade
/usr/bin/install -c COPYING /usr/local/share/linuxband/license.txt
/usr/bin/install -c -t /usr/local/share/linuxband src/main/resources/_

 linuxband

(linuxband:16974): libglade-WARNING **: could not find a parent that handles internal children for `vbox'
13:53:01 ERROR **load_grooves_from_cache Unable to load grooves from cache '/home/jtatum/.linuxband/grooves.cache'
Traceback (most recent call last):
  File "/usr/local/share/linuxband/linuxband/mma/grooves.py", line 142, in __load_grooves_from_cache
    infile = file(fname, 'r')
IOError: [Errno 2] No such file or directory: '/home/jtatum/.linuxband/grooves.cache'
Traceback (most recent call last):
  File "/usr/local/bin/linuxband", line 77, in <module>
    main()
  File "/usr/local/bin/linuxband", line 67, in main
    Gui()
  File "/usr/local/share/linuxband/linuxband/gui/gui.py", line 512, in __init**
    grooves.load_grooves(True)
  File "/usr/local/share/linuxband/linuxband/mma/grooves.py", line 41, in load_grooves
    self.__grooves_model, grooves_list = self.__load_grooves()
  File "/usr/local/share/linuxband/linuxband/mma/grooves.py", line 90, in __load_grooves
    self.__do_load_grooves(grooves_list, self.__config.get_mma_grooves_path())
  File "/usr/local/share/linuxband/linuxband/mma/grooves.py", line 115, in __do_load_grooves
    grooves_list.append([gname, doc, gdesc, author, time, full_name])
UnboundLocalError: local variable 'doc' referenced before assignment

If you need more, I will provide it, just let me know what you need.

John

**Comment by jesuscap5** [comment]
So. What i do after to clone ??
Thank you
